  %1st Leg
        %Solve for ground Link
        groundBx = LegStartX(1) -38 * SF;
        groundBy = LegStartY(1) -7.8 * SF;

        if 1==1
            %Solving First FourBar Linkage
            [Leg(3).Link(1).Pos(A).Cor(X).Rev(T+180), ...
                Leg(3).Link(1).Pos(A).Cor(Y).Rev(T+180), ...
                Leg(3).Link(1).Pos(B).Cor(X).Rev(T+180), ...
                Leg(3).Link(1).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(2).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(2).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(2).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(2).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(3).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(3).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(3).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(3).Pos(B).Cor(Y).Rev(T+180)] = ...
                CrankRockerSolve( LegStartX(1),       LegStartY(1), ...
                groundBx,   groundBy, ...
                FixedPointDist, LinkLength(1), ...
                LinkLength(2),  LinkLength(3), T, Norm, Norm);

        end

        if 1 ==1
            %Solving Second FourBar Linkage
            [Temp5, Temp6, Temp7, Temp8, ...
                Leg(3).Link(4).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(4).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(4).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(4).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(5).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(5).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(5).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(5).Pos(B).Cor(Y).Rev(T+180)] = ...
                CrankRockerSolve( LegStartX(1),       LegStartY(1), ...
                groundBx,   groundBy, ...
                FixedPointDist, LinkLength(1), ...
                LinkLength(4),  LinkLength(5), T, FlipX, Norm);
        end



        if 3==3
            %Solve First 3 Bar
            [Temp1, Temp2, Temp3, Temp4, ...
                Leg(3).Link(7).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(7).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(7).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(7).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(6).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(6).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(6).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(6).Pos(B).Cor(Y).Rev(T+180)] ...
                = ThreeBarSolve(Leg(3).Link(3).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(3).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(3).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(3).Pos(A).Cor(Y).Rev(T+180),...
                LinkLength(3), LinkLength(7), LinkLength(6));
        end

        if 4==4
            %Solving Third FourBar Linkage Using MultiDependancy Solver
            %(uses cordinates from input plus moving frame)

            [Temp1, Temp2, Temp3, Temp4, ...
                Temp5, Temp6, Temp7, Temp8, ...
                Leg(3).Link(9).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(9).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(9).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(9).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(8).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(8).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(8).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(8).Pos(B).Cor(Y).Rev(T+180)] = ...
                MultiDependancyFourBarSolve( Leg(3).Link(6).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(6).Pos(A).Cor(Y).Rev(T+180), ...
                Leg(3).Link(6).Pos(B).Cor(X).Rev(T+180), ...
                Leg(3).Link(6).Pos(B).Cor(Y).Rev(T+180), ...
                Leg(3).Link(5).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(5).Pos(B).Cor(Y).Rev(T+180), ...
                Leg(3).Link(5).Pos(A).Cor(X).Rev(T+180), ...
                Leg(3).Link(5).Pos(A).Cor(Y).Rev(T+180), ...
                LinkLength(6), LinkLength(5), ...
                LinkLength(9),  LinkLength(8), Norm, Norm);
        end
        if 5==5

            %Solve Seconde 3 Bar
            [Temp1, Temp2, Temp3, Temp4, ...
                Leg(3).Link(10).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(10).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(10).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(10).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(11).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(11).Pos(A).Cor(Y).Rev(T+180),...
                Leg(3).Link(11).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(11).Pos(B).Cor(Y).Rev(T+180)] ...
                = ThreeBarSolve(Leg(3).Link(9).Pos(B).Cor(X).Rev(T+180),...
                Leg(3).Link(9).Pos(B).Cor(Y).Rev(T+180),...
                Leg(3).Link(9).Pos(A).Cor(X).Rev(T+180),...
                Leg(3).Link(9).Pos(A).Cor(Y).Rev(T+180),...
                LinkLength(9), LinkLength(10), LinkLength(11));
        end